name: deploy
on:
  # workflow_run:
  #   workflows:
  #     - ci
  #   types: [completed]
  push:
    branches:
      - main
env:
  GCP_REGION: asia-northeast1
  IMAGE_GCP: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_RUN_SERVICE_NAME }}:${{ github.sha }}
jobs:
  deploy_prod:
    name: Deploy app to prod env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: set up gcp
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        run: docker build --target prod -t $IMAGE_GCP .
      - name: Push the docker image to Container Registry
        run: docker push $IMAGE_GCP
      - name: Deploy to Cloud Run
        run: |
            gcloud run deploy $SERVICE_NAME \
              --image $IMAGE_GCP \
              # --port $PORT \
              --project $GCP_PROJECT_ID \
              --region $GCP_REGION \
              --platform=managed \
              --allow-unauthenticated \
              --quiet